server:
  port: 80

spring:
  main:
    allow-bean-definition-overriding: true

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    #url: jdbc:mariadb://localhost:3306/study?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    url: jdbc:mariadb://localhost:3306/study
    username: root
    password: root
    hikari:
      maximum-pool-size: 5
      minimum-idle: 3

  jpa:
    properties:
      hibernate:
        hbm2ddl.auto: validate
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MariaDB103Dialect

logging:
  level:
    root: info
    org.hibernate.type.descriptor.sql: trace
    # org.springframework.web: debug
    #org.hibernate.SQL: debug
    #file:
    #path: target/logs