server:
  port: 80

spring:
  main:
    allow-bean-definition-overriding: true

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    #url: jdbc:mariadb://localhost:3306/study?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    url: jdbc:mariadb://localhost:3306/study
    username: root
    password: root
    hikari:
      maximum-pool-size: 5
      minimum-idle: 3

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

    properties:
      hibernate.show_sql: true
      hibernate.use_sql_comments: true
      hibernate.format_sql: true
      hibernate.query.in_clause_parameter_padding: true
    open-in-view: false
    database-platform: org.hibernate.dialect.MariaDB103Dialect

  security:
    user:
      name: admin
      password: admin

logging:
  level:
    root: info
    org.hibernate.type.descriptor.sql: trace
    #org.hibernate.SQL: debug
    #file:
    #path: target/logs